# Generated by Django 4.2.5 on 2023-09-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('maternelle', 'Maternelle'), ('primaire', 'Primaire'), ('college', 'College'), ('lycee', 'Lycee')], max_length=50)),
                ('total', models.IntegerField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('courses', models.CharField(max_length=100)),
                ('date_join', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField()),
                ('picture', models.ImageField(upload_to='media/prof_pic')),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SessionYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.CharField(max_length=100)),
                ('session_end', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'ROOT'), ('2', 'DG'), ('3', 'DE'), ('4', 'COM'), ('5', 'PROF')], default=1, max_length=50),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('date_join', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField()),
                ('picture', models.ImageField(upload_to='media/student_pic')),
                ('father_name', models.CharField(max_length=100)),
                ('father_profession', models.CharField(max_length=100)),
                ('father_phone', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_profession', models.CharField(max_length=100)),
                ('mother_phone', models.CharField(max_length=100)),
                ('classe_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.classe')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.sessionyear')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prof_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.professor')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.sessionyear'),
        ),
    ]
